### ISSUE TITLE
Add how to start open source and how to make 1st PR section in read me

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Open-Source-Programs#5]

**Comment by Abhirv08** [comment]
@arpit456jain May i do this?

**Comment by arpit456jain** [comment]
Yes @Abhirv08

**Comment by Abhirv08** [comment]
@arpit456jain well, I have a doubt. Where should i add this section in readme file?

**Comment by arpit456jain** [comment]
In the last after the table

**Comment by Abhirv08** [comment]
okay

**Comment by Abhirv08** [comment]
@arpit456jain Should i use pictures too?

**Comment by arpit456jain** [comment]
Yes u can use them
Btw let me tell you one thing this repo is not registered under any program.
Hope you are not doing this under SWOC'21

**Comment by Abhirv08** [comment]
@arpit456jain I love contributing to open source and i am doing for that.

**Comment by arpit456jain** [comment]
Great 👍

**Comment by arpit456jain** [comment]
Join my discord server you will find many cool open source project of different tech stack

**Comment by arpit456jain** [comment]
https://discord.gg/w5nkB88b

**Comment by Abhirv08** [comment]
Thank you
